People:
#   - Name : "Example"
#     Day : "2021-12-16"  # 日期格式为yyyy-MM-dd，若不知道年份则设置为0000
#     Calendar : "lunar"  # 阴历：lunar 阳历：solar
#     DistanceConfig : 1  # 设置生日提前几天提醒, 最大为3, 0为当天提醒
  - Name : "黄雅婷"
    Day : "09-12-23"
    Calendar : "lunar"
    DistanceConfig : 1
