People:
#   - Name : "Example"
#     Day : "2021-12-16"  # 日期格式为yyyy-MM-dd，若不知道年份则设置为0000
#     Calendar : "lunar"  # 阴历：lunar 阳历：solar
#     DistanceConfig : 1  # 设置生日提前几天提醒, 最大为3, 0为当天提醒
  - Name : "Me"
    Day : "2001-12-17"
    Calendar : "solar"
    DistanceConfig : 1
